### PR TITLE
Prune empty samples

### LINKED ISSUE #65: Beta div failing with pathways
Noticed on both live and qa.

Example (qa): 
Screen Shot 2023-12-05 at 6 28 26 AM

R output:
```
Rserve started in non-daemon mode.
[1] "starting beta diversity computation"

2023-12-05 10:41:13 Received df table with 574 samples and 435 taxa.

2023-12-05 10:41:13 Replaced NAs with 0

2023-12-05 10:41:14 Computed dissimilarity matrix.
Error in eigen(delta1) : infinite or missing values in 'x'
In addition: Warning messages:
1: no function found corresponding to methods exports from ‘veupathUtils’ for: ‘asJSON’
2: replacing previous import ‘data.table::as.data.table’ by ‘veupathUtils::as.data.table’ when loading ‘plot.data’
3: replacing previous import ‘veupathUtils::toJSON’ by ‘jsonlite::toJSON’ when loading ‘plot.data’
4: replacing previous import ‘data.table::as.data.table’ by ‘veupathUtils::as.data.table’ when loading ‘microbiomeComputations’
5: In data.table::fread("beta_div_input", select = c(OBI_0002623.WholeMetagenomeSequencingAssay_stable_id = "double",  :
  Attempt to override column 1 <<OBI_0002623.WholeMetagenomeSequencingAssay_stable_id>> of inherent type 'string' down to 'float64' ignored. Only overrides to a higher type are currently supported. If this was intended, please coerce to the lower type afterwards.
6: In data.table::fread("beta_div_input", select = c(OBI_0002623.WholeMetagenomeSequencingAssay_stable_id = "double",  :
  Attempt to override column 2 <<EUPATH_0000609.Sample_stable_id>> of inherent type 'string' down to 'float64' ignored. Only overrides to a higher type are currently supported. If this was intended, please coerce to the lower type afterwards.
7: In data.table::fread("beta_div_input", select = c(OBI_0002623.WholeMetagenomeSequencingAssay_stable_id = "double",  :
  Attempt to override column 3 <<EUPATH_0000096.Participant_stable_id>> of inherent type 'string' down to 'float64' ignored. Only overrides to a higher type are currently supported. If this was intended, please coerce to the lower type afterwards.
8: In vegan::vegdist(df[, -..allIdColumns], method = method, binary = TRUE) :
  you have empty rows: their dissimilarities may be
                 meaningless in method “bray”
9: In vegan::vegdist(df[, -..allIdColumns], method = method, binary = TRUE) :
  missing values in results
```

### LINKED ISSUE #76: Differential abundance: failure with corral data
From Dan B on live site

image

So far i know
- HMP WGS on qa works (sex as group comparison variable), but only two organisms have results
- Bonus computation fails on qa

Logs from the bonus failure:
```
[1] "starting differential abundance computation"

2024-01-08 17:30:41 Received abundance table with 1279 samples and 21 taxa.

2024-01-08 17:30:41 Found 1279 samples with a value for EUPATH_0000096.EUPATH_0000639 in either groupA or groupB. The calculation will continue with only these samples.
[1] "Creating output folder"
2024-01-08 17:30:41 INFO::Writing function arguments to log file
2024-01-08 17:30:41 INFO::Verifying options selected are valid
2024-01-08 17:30:41 INFO::Determining format of input files
2024-01-08 17:30:41 INFO::Input format is data samples as rows and metadata samples as rows
2024-01-08 17:30:41 INFO::Formula for fixed effects: expr ~  EUPATH_0000096.EUPATH_0000639
2024-01-08 17:30:41 INFO::Filter data based on min abundance and min prevalence
2024-01-08 17:30:41 INFO::Total samples in data: 1279
2024-01-08 17:30:41 INFO::Min samples required with min abundance for a feature not to be filtered: 127.900000
2024-01-08 17:30:41 INFO::Total filtered features: 18
2024-01-08 17:30:41 INFO::Filtered feature names from abundance and prevalence filtering: OBI_0002623.EUPATH_0009269_Ascomycota_Saccharomycetales_Debaryomycetaceae_Candida_Candida_orthopsilosis, OBI_0002623.EUPATH_0009269_Ascomycota_Saccharomycetes_Saccharomycetales_Candida_Candida_sake, OBI_0002623.EUPATH_0009269_Ascomycota_Saccharomycetes_Saccharomycetales_Debaryomycetaceae_, OBI_0002623.EUPATH_0009269_Ascomycota_accharomycetales_Metschnikowiaceae_Clavispora_Candida_intermedia, OBI_0002623.EUPATH_0009269_Ascomycota_aromycetales_Saccharomycodaceae_Hanseniaspora_Hanseniaspora_uvarum, OBI_0002623.EUPATH_0009269_Ascomycota_aromycetes_Saccharomycetales_Pichiaceae_Pichia_Pichia_kudriavzevii, OBI_0002623.EUPATH_0009269_Ascomycota_ccharomycetales_Metschnikowiaceae_Clavispora_Clavispora_lusitaniae, OBI_0002623.EUPATH_0009269_Ascomycota_ccharomycetales_Saccharomycetaceae_Nakaseomyces_Candida_glabrata, OBI_0002623.EUPATH_0009269_Ascomycota_cetales_Trichomonascaceae_Wickerhamiella_Wickerhamiella_pararugosa, OBI_0002623.EUPATH_0009269_Ascomycota_cetes_Saccharomycetales_Debaryomycetaceae_Candida_Candida_albicans, OBI_0002623.EUPATH_0009269_Ascomycota_haromycetales_Debaryomycetaceae_Debaryomyces_Debaryomyces_hansenii, OBI_0002623.EUPATH_0009269_Ascomycota_omycetes_Eurotiales_Aspergillaceae_Aspergillus_Aspergillus_sydowii, OBI_0002623.EUPATH_0009269_Ascomycota_s_Saccharomycetales_Debaryomycetaceae_Candida_Candida_parapsilosis, OBI_0002623.EUPATH_0009269_Ascomycota_tes_Saccharomycetales_Debaryomycetaceae_Candida_Candida_tropicalis, OBI_0002623.EUPATH_0009269_Ascomycota_ycetales_Saccharomycetaceae_Saccharomyces_Saccharomyces_cerevisiae, OBI_0002623.EUPATH_0009269_Basidiomycota_Sporidiobolales_Sporidiobolaceae_Rhodotorula_Rhodotorula_sp_JG_1b, OBI_0002623.EUPATH_0009269_Basidiomycota_cetes_Malasseziales_Malasseziaceae_Malassezia_Malassezia_restricta, OBI_0002623.EUPATH_0009269_Basidiomycota_mycetes_Malasseziales_Malasseziaceae_Malassezia_Malassezia_globosa
2024-01-08 17:30:41 INFO::Total filtered features with variance filtering: 0
2024-01-08 17:30:41 INFO::Filtered feature names from variance filtering:
2024-01-08 17:30:41 INFO::Running selected normalization method: TSS
2024-01-08 17:30:41 INFO::Applying z-score to standardize continuous metadata
2024-01-08 17:30:41 INFO::Running selected transform method: LOG
2024-01-08 17:30:41 INFO::Running selected analysis method: LM
Error in seq_len(ncol(features)) :
  argument must be coercible to non-negative integer
```

So that's the issue. The variance filter chops off the features.

Probably a good reason to prioritize adding a way to see the logs of each computation

### PR DESCRIPTION
**Pull request by d-callan**
resolves #65 
might resolve #76 but needs confirmation

AbundanceData has a method getAbundances, which will now only return samples that actually have data for at least one variable/ feature/ taxa/ pathway/ etc

where computes werent already using getAbundances, theyve been updated to do that

### CODE REVIEW

File: R/methods-AbundanceData.R [hunk 1]
```diff
@@ -18,20 +18,29 @@ setMethod("getAbundances", signature("AbundanceData"), function(object, ignoreIm
   ignoreImputeZero <- veupathUtils::matchArg(ignoreImputeZero)
   includeIds <- veupathUtils::matchArg(includeIds)
   dt <- object@data
+  allIdColumns <- c(object@recordIdColumn, object@ancestorIdColumns)
```
Comment (asizemore) [inline R/methods-AbundanceData.R:21]: do we not have a getIdColumns function? Seems useful

File: R/methods-AbundanceData.R [hunk 2]
```diff
@@ -18,20 +18,29 @@ setMethod("getAbundances", signature("AbundanceData"), function(object, ignoreIm
...
   # Check that incoming dt meets requirements
   if (!inherits(dt, 'data.table')) {
     # this might technically be bad form, but i think its ok in this context
     data.table::setDT(dt)
   }
 
+  if (object@removeEmptySamples) {
+    dt.noIds <- dt[, -..allIdColumns]
+    # Remove samples with NA in all columns
+    dt <- dt[rowSums(is.na(dt.noIds)) != ncol(dt.noIds),]
```
Comment (asizemore) [inline R/methods-AbundanceData.R:32]: the one case this will miss is if a row has NAs and Os and nothing else

File: R/methods-AbundanceData.R (hunk 1 above)
Comment (asizemore) [reply R/methods-AbundanceData.R:21]: just suggesting

File: R/methods-AbundanceData.R [hunk 3]
```diff
@@ -67,8 +77,18 @@ setMethod("getSampleMetadata", signature("AbundanceData"), function(object, asCo
     dt <- data.table::copy(dt)
   }
 
+  if (object@removeEmptySamples) {
+    # not using getAbundances here bc i want the empty samples here
```
Comment (asizemore) [inline R/methods-AbundanceData.R:81]: why not make a findEmptySamples function that returns the sample names? We could use that in this fn, the get abundances fn, and if we wanted to print out the names of empty samples elsewhere.

File: tests/testthat/test-betaDiv.R [hunk 4]
```diff
@@ -39,7 +40,7 @@ test_that('betaDiv returns a correctly formatted data.table', {
               recordIdColumn = 'entity.SampleID')
 
   dt <- betaDiv(data, method='bray', verbose=F)@data
-  expect_equal(nrow(dt), nrow(df))
+  expect_equal(nrow(dt), nrow(df) - nNAs)
```
Comment (asizemore) [inline tests/testthat/test-betaDiv.R:43]: if we don't remove empty samples, shouldn't this be just nrow(df)? The nNAs should still be in there

**Review by asizemore — COMMENTED** [review]
Some computation results used to have a slot for "removedSamples" or something similar. This was in preparation for something like we're doing now where we drop certain samples. We don't need to bring that slot back unless we're going to use it, but it might be helpful to also have R print out the list of removed samples, or at least the number of removed samples, and why.

File: R/methods-AbundanceData.R (hunk 3 above)
Comment (d-callan) [reply R/methods-AbundanceData.R:81]: im a little nervous at the idea of relying on/ interacting w the id cols too much. im not sure i want to be doing things like validating that we have unique ids etc here..
